import { v2 as cloudinary } from 'cloudinary';
import { writeFileSync } from 'fs';

if (!process.env.CLOUDINARY_API_KEY || !process.env.CLOUDINARY_API_SECRET) {
  console.log('Skipping image generation — CLOUDINARY_API_KEY/SECRET not set.');
  process.exit(0);
}

cloudinary.config({
  cloud_name: 'dlgytpexo',
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const CLOUD = 'dlgytpexo';

const SECTIONS = [
  { tag: 'automotive gallery', export: 'AutomotiveImages', variable: 'autoImages' },
  { tag: 'travel gallery',     export: 'TravelImages',     variable: 'travelImages' },
];

function toUrl(publicId) {
  return `https://res.cloudinary.com/${CLOUD}/image/upload/f_auto,q_auto,w_1000/${publicId}`;
}

function toAlt(publicId) {
  const name = publicId.split('/').pop();
  return name
    .replace(/_[a-z0-9]{4,}$/, '') // strip cloudinary suffix e.g. _jlqe1s
    .replace(/^[^-]+-/, '')         // strip category prefix e.g. "automotive-"
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}

try {
  const results = {};
  for (const section of SECTIONS) {
    const { resources } = await cloudinary.api.resources_by_tag(section.tag, { max_results: 100, context: true });
    results[section.variable] = resources
      .sort((a, b) => {
        const aOrder = parseInt(a.context?.custom?.order ?? 999);
        const bOrder = parseInt(b.context?.custom?.order ?? 999);
        return aOrder - bOrder;
      })
      .map(r => ({
        thumbSrc: toUrl(r.public_id),
        alt: r.context?.custom?.alt ?? toAlt(r.public_id),
        width: r.width,
        height: r.height,
      }));
    console.log(`${section.tag}: ${resources.length} images`);
  }

  const output = `// Auto-generated by scripts/generate-images.mjs — do not edit manually

${SECTIONS.map(s => `const ${s.variable} = ${JSON.stringify(results[s.variable], null, 2)};`).join('\n\n')}

${SECTIONS.map(s => `export const ${s.export} = ${s.variable};`).join('\n')}
`;

  writeFileSync('src/components/imageGallery/images.jsx', output);
  console.log('✓ Generated src/components/imageGallery/images.jsx');
} catch (err) {
  console.warn(`⚠ Cloudinary fetch failed — keeping existing images.jsx\n  ${err.message}`);
  process.exit(0);
}
